<a href="https://colab.research.google.com/github/Bencki/DataScienceCourse/blob/main/basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy

##Podstawy


In [96]:
import numpy as np
import pandas as pd
np.__version__

'1.19.5'

In [2]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly c

In [3]:
x = np.array([1,3])

In [4]:
x

array([1, 3])

In [5]:
print(x)

[1 3]


In [6]:
x.ndim, x.shape, x.size, x.dtype

(1, (2,), 2, dtype('int64'))

In [7]:
x = np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [8]:
x.ndim, x.shape, x.size, x.dtype

(2, (2, 2), 4, dtype('int64'))

In [9]:
x = np.array(
    [[[4,3,1],
      [3,2,3]],
     
     [[4,3,2],
      [5,6,7]],
     
     [[5,6,7],
      [7,8,9]]]
)
print(x)

[[[4 3 1]
  [3 2 3]]

 [[4 3 2]
  [5 6 7]]

 [[5 6 7]
  [7 8 9]]]


In [10]:
x.ndim, x.shape, x.size, x.dtype

(3, (3, 2, 3), 18, dtype('int64'))

##Typy danych

In [11]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [12]:
B = np.array([1.0, 2.0, 3.0])
B.dtype

dtype('float64')

In [13]:
C = np.array([1, 2, 3], dtype='float')
C.dtype

dtype('float64')

In [14]:
D = np.array([1.1, 2.6, 3,9], dtype='int')
D

array([1, 2, 3, 9])

In [15]:
E = np.array([24, 120, 230], dtype=np.uint8)
E.dtype

dtype('uint8')

##Tworzenie tablic

In [16]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [17]:
np.ones(shape=(3,6), dtype='int')

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [18]:
np.full(shape=(3, 4), fill_value=4, dtype='int')

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [21]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [22]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [23]:
A = np.arange(15)

In [24]:
A = A.reshape((3,5))
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

##Podstawowe operacje na tablicach

In [25]:
A = np.array([1,2,3,4])
B = np.array([5,6,7,8])

In [26]:
print(A)
print(B)

[1 2 3 4]
[5 6 7 8]


In [27]:
print(A + B) #.add()
print(A - B) #.subtract()
print(A * B) #.multiply()
print(A / B) #.divide()
print(A + 3)
#itd itp

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[4 5 6 7]


In [28]:
A = np.array([[1,3], [-2,0]])
B = np.array([[6,0], [-1,2]])

In [29]:
print(A * B) #mnożenie element po elemencie

[[6 0]
 [2 0]]


In [30]:
print(np.dot(A, B)) #mnożenie macieżowe
print(A.dot(B))  #lub A @ B
print(B.dot(A))  #lub B @ A

[[  3   6]
 [-12   0]]
[[  3   6]
 [-12   0]]
[[ 6 18]
 [-5 -3]]


##Liczby pseudolosowe

In [31]:
np.random.seed(0)

In [32]:
np.random.randn(10)

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ])

In [33]:
np.random.randn(10,4) #rozkład normalny

array([[ 0.14404357,  1.45427351,  0.76103773,  0.12167502],
       [ 0.44386323,  0.33367433,  1.49407907, -0.20515826],
       [ 0.3130677 , -0.85409574, -2.55298982,  0.6536186 ],
       [ 0.8644362 , -0.74216502,  2.26975462, -1.45436567],
       [ 0.04575852, -0.18718385,  1.53277921,  1.46935877],
       [ 0.15494743,  0.37816252, -0.88778575, -1.98079647],
       [-0.34791215,  0.15634897,  1.23029068,  1.20237985],
       [-0.38732682, -0.30230275, -1.04855297, -1.42001794],
       [-1.70627019,  1.9507754 , -0.50965218, -0.4380743 ],
       [-1.25279536,  0.77749036, -1.61389785, -0.21274028]])

In [34]:
np.random.rand(10,4) #rozkład jednostajny na przedziale domyślnie [0,1)

array([[0.15896958, 0.11037514, 0.65632959, 0.13818295],
       [0.19658236, 0.36872517, 0.82099323, 0.09710128],
       [0.83794491, 0.09609841, 0.97645947, 0.4686512 ],
       [0.97676109, 0.60484552, 0.73926358, 0.03918779],
       [0.28280696, 0.12019656, 0.2961402 , 0.11872772],
       [0.31798318, 0.41426299, 0.0641475 , 0.69247212],
       [0.56660145, 0.26538949, 0.52324805, 0.09394051],
       [0.5759465 , 0.9292962 , 0.31856895, 0.66741038],
       [0.13179786, 0.7163272 , 0.28940609, 0.18319136],
       [0.58651293, 0.02010755, 0.82894003, 0.00469548]])

In [35]:
A = np.random.randint(low=10, high=101, size=5) 
A

array([12, 13, 23, 50, 82])

In [36]:
np.random.choice(A) #równiez wartości typu 'str'

50

In [37]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.random.shuffle(data)
data

array([5, 7, 9, 1, 6, 3, 4, 0, 2, 8])

##Podstawowe funkcje

In [39]:
print(np.exp(1))
print(np.sqrt(9))

2.718281828459045
3.0


In [40]:
print(np.all([2,3,5]))
print(np.all([2,3,0]))

True
False


In [41]:
np.any([1, 2, 1])

True

In [42]:
A = np.random.rand(5)
A

array([0.84640867, 0.69947928, 0.29743695, 0.81379782, 0.39650574])

In [43]:
np.argmax(A)

0

In [44]:
A[np.argmax(A)]

0.8464086724711278

In [45]:
np.argsort(A)

array([2, 4, 1, 3, 0])

##Indeksowanie

In [46]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [47]:
# A[idx], A[start : stop], A[: stop], A[start :]
# tak samo jak w pythonie

In [48]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [49]:
A[0] #wiersze

array([0, 1, 2, 3, 4])

In [50]:
A[:, 0] #kolumny

array([ 0,  5, 10, 15])

In [51]:
A[1, 1] #konkretny element

6

In [52]:
A[1:3, 1:4] #fragment

array([[ 6,  7,  8],
       [11, 12, 13]])

##Iteracja po tablicach

In [53]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [54]:
for row in A:  #iterowanie po wierszach
    print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [55]:
for column in A.transpose():  #iterowanie po kolumnach
    print(column)

[ 0  5 10 15]
[ 1  6 11 16]
[ 2  7 12 17]
[ 3  8 13 18]
[ 4  9 14 19]


In [56]:
for item in A.flat:   #iterowanie po każdym elemencie
    print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


##Zmiana rozmiaru tablic

In [57]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [58]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [59]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

 ##Maski logiczne

In [60]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10,-1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [61]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [62]:
A[A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [63]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

##Algebra liniowa

###Norma wektora, długość wektora w R^2

${\mathbf  {v}} = [v_{1}, v_{2}]$   
$\left\|{\mathbf  {v}}\right\|={\sqrt  {v_{1}^{2}+v_{2}^{2}}}$

In [64]:
v1 = np.array([-1,4])
v1

array([-1,  4])

In [65]:
np.linalg.norm(v1)

4.123105625617661

###Norma euklidesowa w R^n

$\left\|{\mathbf  {v}}\right\|={\sqrt  {v_{1}^{2}+v_{2}^{2}+\cdots +v_{n}^{2}}}$

In [66]:
v2 = np.array([-10, 10, 13])
v2

array([-10,  10,  13])

In [67]:
np.linalg.norm(v2)

19.209372712298546

###Odległość dwóch punktów na płaszczyźnie oraz w przestrzeni R^n

 \begin{aligned}d(\mathbf {p} ,\mathbf {q} )=d(\mathbf {q} ,\mathbf {p} )&={\sqrt {(q_{1}-p_{1})^{2}+(q_{2}-p_{2})^{2}+\cdots +(q_{n}-p_{n})^{2}}}\\[8pt]&={\sqrt {\sum _{i=1}^{n}(q_{i}-p_{i})^{2}}}\end{aligned}

In [68]:
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p-q)

5.0

In [69]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(p-q)

5.0990195135927845

###Mnożenie macierzy

$${A} ={\begin{bmatrix}a_{11}&a_{12}&\cdots &a_{1n}\\a_{21}&a_{22}&\cdots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{m1}&a_{m2}&\cdots &a_{mn}\\\end{bmatrix}}$$
A - macierz wymairu $m\ x\ n$

$$ {B} ={\begin{bmatrix}b_{11}&b_{12}&\cdots &b_{1p}\\b_{21}&b_{22}&\cdots &b_{2p}\\\vdots &\vdots &\ddots &\vdots \\b_{n1}&b_{n2}&\cdots &b_{np}\\\end{bmatrix}}$$
B - macierz wymairu $n\ x\ p$

$$C = AB$$ 
C - macierz wymiaru $m\ x\ p$  
Aby móc pomnożyć dwie macierze liczba liczba kolumn w lewej macierzy musi zgadzać się z liczbą wierszy prawej macierzy.

Mnożenie macierzy nie jest przemienne! Tzn. $$AB \neq BA$$

In [70]:
X = np.array([[5,3], [3,9]])
Y = np.array([[1], [-1]])
print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [71]:
Z = np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [72]:
X = np.array([[2, -1, 3],
              [3, 1, 0]])
Y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])
print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [73]:
Z = np.dot(X, Y)
Z

array([[13,  9, -4],
       [ 6,  2, -1]])

### <a name='a6'></a> Wyznacznik macierzy

$${\displaystyle A={\begin{bmatrix}a_{11}&a_{12}&\dots &a_{1n}\\a_{21}&a_{22}&\dots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{n1}&a_{n2}&\dots &a_{nn}\end{bmatrix}}}$$
$A$ - macierz wymiaru nxn

#### Oznaczenia:

${\displaystyle |A|=\left|{\begin{array}{c}a_{11}&a_{12}&\dots &a_{1n}\\a_{21}&a_{22}&\dots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{n1}&a_{n2}&\dots &a_{nn}\end{array}}\right|} $  lub  $ {\displaystyle \det A=\det {\begin{bmatrix}a_{11}&a_{12}&\dots &a_{1n}\\a_{21}&a_{22}&\dots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{n1}&a_{n2}&\dots &a_{nn}\end{bmatrix}}}$

#### Przykład:
${\displaystyle \det A={\begin{vmatrix}a_{11}&a_{12}\\a_{21}&a_{22}\end{vmatrix}}=a_{11}a_{22}-a_{12}a_{21}}$

${\displaystyle \det A={\begin{vmatrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\a_{31}&a_{32}&a_{33}\end{vmatrix}}=a_{11}a_{22}a_{33}+a_{21}a_{32}a_{13}+a_{31}a_{12}a_{23}-a_{21}a_{12}a_{33}-a_{11}a_{32}a_{23}-a_{31}a_{22}a_{13}}$

${\displaystyle \det A={\begin{vmatrix}2&4\\-1&3\end{vmatrix}}=2\cdot3-4\cdot(-1)} = 6 + 4 = 10 $


In [74]:
A = np.array([[2, 4], [-1, 3]])
A

array([[ 2,  4],
       [-1,  3]])

In [75]:
round(np.linalg.det(A))

10

### <a name='a7'></a> Ślad macierzy

$${\displaystyle A={\begin{bmatrix}a_{11}&a_{12}&\dots &a_{1n}\\a_{21}&a_{22}&\dots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{n1}&a_{n2}&\dots &a_{nn}\end{bmatrix}}}$$
$A$ - macierz wymiaru nxn

${\displaystyle \operatorname {tr} (A)=\sum _{i=1}^{n}a_{ii}=a_{11}+a_{22}+\dots +a_{nn}}$

#### Przykład:
$A = \begin{bmatrix}2&4\\-1&3\end{bmatrix}$

${\displaystyle \operatorname {tr} (A)=\sum _{i=1}^{2}a_{ii}=a_{11}+a_{22} = 2 + 3 = 5}$

In [76]:
A = np.array([[2, 4], [-1, 3]])
A

array([[ 2,  4],
       [-1,  3]])

In [77]:
np.trace(A)

5

###  <a name='a8'></a>  Macierz jednostkowa 

Macierz jednostkowa - macierz kwadratowa, której współczynniki podane są wzorem:
$${\displaystyle a_{ij}={\begin{cases}1\quad {\text{dla}}\quad i=j\\[2pt]0\quad {\text{dla}}\quad i\neq j\end{cases}}}$$

#### Przykłady
${\displaystyle I_{1}={\begin{bmatrix}1\end{bmatrix}},\;I_{2}={\begin{bmatrix}1&0\\0&1\end{bmatrix}},\;I_{3}={\begin{bmatrix}1&0&0\\0&1&0\\0&0&1\end{bmatrix}}}$

In [78]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

### <a name='a9'></a>  Macierz odwrotna

$A$ - macierz kwadratowa stopnia $n$. Macierz $A$ posiada macierz odwrotną, gdy istnieje macierz $B$, taka, że
$$AB = BA = I$$

$A = \begin{bmatrix}2&4\\-1&3\end{bmatrix}$

In [79]:
A

array([[ 2,  4],
       [-1,  3]])

In [80]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [81]:
np.set_printoptions(precision=4, suppress=True)

np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

### <a name='a10'></a> Macierz transponowana

Zamiana wierszy na kolumny i kolumny na wiersze.

#### Przykład 1:

$A = \begin{bmatrix}2&4\\-1&3\end{bmatrix}$,
$A^{T} = \begin{bmatrix}2&-1\\4&3\end{bmatrix}$

#### Przykład 2:
$A = \begin{bmatrix}2&1&-1\\0&-1&2\end{bmatrix}$,
$A^{T} = \begin{bmatrix}2&0\\1&-1\\-1&2\end{bmatrix}$

In [82]:
A

array([[ 2,  4],
       [-1,  3]])

In [83]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [84]:
A.T

array([[ 2, -1],
       [ 4,  3]])

### <a name='a11'></a> Rozwiązywanie układów równań
Rozważmy układ równań $U$:  
$${\displaystyle \mathrm {U} \colon {\begin{cases}{\begin{matrix}a_{11}x_{1}&+&a_{12}x_{2}&+&\dots &+&a_{1n}x_{n}&=b_{1},\\a_{21}x_{1}&+&a_{22}x_{2}&+&\dots &+&a_{2n}x_{n}&=b_{2},\\\vdots &&\vdots &&\ddots &&\vdots &\vdots \\a_{m1}x_{1}&+&a_{m2}x_{2}&+&\dots &+&a_{mn}x_{n}&=b_{m}.\end{matrix}}\end{cases}}.}$$

Wykorzystując macierze możemy to przedstawić następująco:

$${\begin{bmatrix}a_{11}&a_{12}&\dots &a_{1n}\\a_{21}&a_{22}&\dots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{m1}&a_{m2}&\dots &a_{mn}\end{bmatrix}}{\begin{bmatrix}x_{1}\\x_{2}\\\vdots \\x_{n}\end{bmatrix}}={\begin{bmatrix}b_{1}\\b_{2}\\\vdots \\b_{m}\end{bmatrix}}$$
I w zapisie skrótowym:
$$\mathbf {AX} =\mathbf {B}$$

Gdzie:  
$A = {\begin{bmatrix}a_{11}&a_{12}&\dots &a_{1n}\\a_{21}&a_{22}&\dots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{m1}&a_{m2}&\dots &a_{mn}\end{bmatrix}}$ - macierz współczynników

${\displaystyle \mathbf {B} =[b_{1},b_{2},\dots ,b_{m}]} $ - wektor wyrazów wolnych  
${\mathbf  X}=[x_{1},x_{2},\dots ,x_{n}] $ - wektor niewiadomych

Jeśli macierz układu $A$ jest macierzą kwadratową, to oznaczoność układu jest równoważna jej odwracalności, tzn.
$$\mathbf {AX} =\mathbf {B}$$
$${\displaystyle \mathbf {A} ^{-1}\mathbf {AX} =\mathbf {A} ^{-1}\mathbf {B}} $$
$$\mathbf {X} =\mathbf {A} ^{-1}\mathbf {B} .$$

#### Przykład:
Rozważmy układ równań:
$$\begin{cases}2x + 4y = 10 \\ x - y = -1 \end{cases}$$  
Rozwiązaniem jest para liczb:
$$\begin{cases}x = 1 \\ y = 2 \end{cases}$$  






In [85]:
A = np.array([[2, 4], [1, -1]])
A

array([[ 2,  4],
       [ 1, -1]])

In [86]:
B = np.array([[10], [-1]])
B

array([[10],
       [-1]])

In [87]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.1667,  0.6667],
       [ 0.1667, -0.3333]])

In [88]:
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])

##Funkcje statystyczne

In [89]:
price = np.array([[12.40, 12.80, 11.90, 12.60, 1000],
                  [12.50, 13.00, 11.70, 12.20, 2000],
                  [12.20, 13.40, 12.20, 13.20, 1500]])
print(price)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]]


In [90]:
price.sum()

4650.1

In [91]:
price.sum(axis=0) #po kolumnach, axis=0 - po wierszach

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [92]:
np.sum(price, axis=0)

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [93]:
np.mean(price, axis=0)

array([  12.3667,   13.0667,   11.9333,   12.6667, 1500.    ])

In [94]:
#itd itp

#Pandas

##Series i DataFrame

In [101]:
s = pd.Series(data=[3, 2, 4, 6], index=['a', 'b', 'c', 'd'], name='sample')
s

a    3
b    2
c    4
d    6
Name: sample, dtype: int64

nan

In [104]:
s = pd.Series(data=[3, np.nan, 4, 6], index=['a', 'b', 'c', 'd'], name='sample')
s

a    3.0
b    NaN
c    4.0
d    6.0
Name: sample, dtype: float64

In [106]:
s = pd.Series(data=[True, False, False])
s

0     True
1    False
2    False
dtype: bool

In [110]:
s = pd.Series(data=np.arange(10, 20), index=pd.date_range(start='20200101', periods=10))
s

2020-01-01    10
2020-01-02    11
2020-01-03    12
2020-01-04    13
2020-01-05    14
2020-01-06    15
2020-01-07    16
2020-01-08    17
2020-01-09    18
2020-01-10    19
Freq: D, dtype: int64

In [113]:
s = pd.Series(data=['python', 'java', 'sql'], name='languages')
s

0    python
1      java
2       sql
Name: languages, dtype: object

In [114]:
type(s)

pandas.core.series.Series

In [115]:
s.index

RangeIndex(start=0, stop=3, step=1)

In [116]:
s = pd.Series(data=np.arange(10, 20), index=pd.date_range(start='20200101', periods=10))
s

2020-01-01    10
2020-01-02    11
2020-01-03    12
2020-01-04    13
2020-01-05    14
2020-01-06    15
2020-01-07    16
2020-01-08    17
2020-01-09    18
2020-01-10    19
Freq: D, dtype: int64

In [117]:
s.index

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10'],
              dtype='datetime64[ns]', freq='D')

In [119]:
s.values

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [120]:
price = pd.Series(data={'Apple':200, 'CD Projekt' : 60,  'Amazon':1900})
price

Apple          200
CD Projekt      60
Amazon        1900
dtype: int64

In [122]:
price['CD Projekt']

60

In [123]:
price[1]

60

In [124]:
price.count()

3

In [125]:
price.value_counts()

60      1
1900    1
200     1
dtype: int64

In [126]:
price.sum()

2160

In [127]:
price.min()

60

In [128]:
price.describe()

count       3.000000
mean      720.000000
std      1024.304642
min        60.000000
25%       130.000000
50%       200.000000
75%      1050.000000
max      1900.000000
dtype: float64

In [138]:
price = pd.Series(data={'Apple':200, 'CD Projekt' : 60,  'Amazon':1900, 'KGHM':np.nan})
price

Apple          200.0
CD Projekt      60.0
Amazon        1900.0
KGHM             NaN
dtype: float64

In [139]:
price.count()

3

In [140]:
price.describe()

count       3.000000
mean      720.000000
std      1024.304642
min        60.000000
25%       130.000000
50%       200.000000
75%      1050.000000
max      1900.000000
dtype: float64

In [141]:
price.nlargest(2)

Amazon    1900.0
Apple      200.0
dtype: float64

In [142]:
price.sort_values()

CD Projekt      60.0
Apple          200.0
Amazon        1900.0
KGHM             NaN
dtype: float64

In [143]:
price_ = price.apply(lambda x: x * 3.8)

In [145]:
df = pd.DataFrame(data=[12, 12, 32])
df

0
0  12
1  12
2  32

In [146]:
df = pd.DataFrame(data=[12, 12, 32], index=['first', 'second', 'third'], columns=['col_1'])
df

col_1
first      12
second     12
third      32

In [147]:
df = pd.DataFrame(data={'WIG20': ['PKN Orlen', 'PKO BP'],
                        'mWIG40' : ['Amica', 'Playway']})
df

WIG20   mWIG40
0  PKN Orlen    Amica
1     PKO BP  Playway

In [150]:
df = pd.DataFrame(data=[[10, 12, 13], [23, 12, 10]], index=['first', 'second'], columns=['col_1', 'col_2', 'col_3'])
df

col_1  col_2  col_3
first      10     12     13
second     23     12     10

In [151]:
df.columns

Index(['col_1', 'col_2', 'col_3'], dtype='object')

In [152]:
df.index

Index(['first', 'second'], dtype='object')

In [153]:
df.values

array([[10, 12, 13],
       [23, 12, 10]])

In [155]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, first to second
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col_1   2 non-null      int64
 1   col_2   2 non-null      int64
 2   col_3   2 non-null      int64
dtypes: int64(3)
memory usage: 64.0+ bytes


In [158]:
df.describe()

col_1  col_2     col_3
count   2.000000    2.0   2.00000
mean   16.500000   12.0  11.50000
std     9.192388    0.0   2.12132
min    10.000000   12.0  10.00000
25%    13.250000   12.0  10.75000
50%    16.500000   12.0  11.50000
75%    19.750000   12.0  12.25000
max    23.000000   12.0  13.00000

In [159]:
df.describe().T

count  mean       std   min    25%   50%    75%   max
col_1    2.0  16.5  9.192388  10.0  13.25  16.5  19.75  23.0
col_2    2.0  12.0  0.000000  12.0  12.00  12.0  12.00  12.0
col_3    2.0  11.5  2.121320  10.0  10.75  11.5  12.25  13.0

In [162]:
df['col_1']
type(df['col_1'])

pandas.core.series.Series

In [163]:
df[['col_1']]
type(df[['col_1']])

pandas.core.frame.DataFrame

In [166]:
df.columns = ['a', 'b', 'c']

In [167]:
df.a

first     10
second    23
Name: a, dtype: int64

In [168]:
df['d'] = df.a + df.c

In [169]:
df

a   b   c   d
first   10  12  13  23
second  23  12  10  33

In [170]:
df.loc['first']

a    10
b    12
c    13
d    23
Name: first, dtype: int64

In [172]:
df.iloc[0]

a    10
b    12
c    13
d    23
Name: first, dtype: int64

In [174]:
df.loc['first', 'b']

12

In [175]:
df.loc[:, 'b']

first     12
second    12
Name: b, dtype: int64