<a href="https://colab.research.google.com/github/Bencki/DataScienceCourse/blob/main/basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy

##Podstawy


In [4]:
import numpy as np
np.__version__

'1.19.5'

In [ ]:
help(np.array)

In [9]:
x = np.array([1,3])

In [10]:
x

array([1, 3])

In [11]:
print(x)

[1 3]


In [17]:
x.ndim, x.shape, x.size, x.dtype

(1, (2,), 2, dtype('int64'))

In [19]:
x = np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [20]:
x.ndim, x.shape, x.size, x.dtype

(2, (2, 2), 4, dtype('int64'))

In [24]:
x = np.array(
    [[[4,3,1],
      [3,2,3]],
     
     [[4,3,2],
      [5,6,7]],
     
     [[5,6,7],
      [7,8,9]]]
)
print(x)

[[[4 3 1]
  [3 2 3]]

 [[4 3 2]
  [5 6 7]]

 [[5 6 7]
  [7 8 9]]]


In [25]:
x.ndim, x.shape, x.size, x.dtype

(3, (3, 2, 3), 18, dtype('int64'))

##Typy danych

In [26]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [27]:
B = np.array([1.0, 2.0, 3.0])
B.dtype

dtype('float64')

In [28]:
C = np.array([1, 2, 3], dtype='float')
C.dtype

dtype('float64')

In [31]:
D = np.array([1.1, 2.6, 3,9], dtype='int')
D

array([1, 2, 3, 9])

In [33]:
E = np.array([24, 120, 230], dtype=np.uint8)
E.dtype

dtype('uint8')

##Tworzenie tablic

In [35]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [36]:
np.ones(shape=(3,6), dtype='int')

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [37]:
np.full(shape=(3, 4), fill_value=4, dtype='int')

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [38]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [40]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [41]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [42]:
A = np.arange(15)

In [46]:
A = A.reshape((3,5))
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

##Podstawowe operacje na tablicach

In [47]:
A = np.array([1,2,3,4])
B = np.array([5,6,7,8])

In [48]:
print(A)
print(B)

[1 2 3 4]
[5 6 7 8]


In [58]:
print(A + B) #.add()
print(A - B) #.subtract()
print(A * B) #.multiply()
print(A / B) #.divide()
print(A + 3)
#itd itp

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[4 5 6 7]


In [63]:
A = np.array([[1,3], [-2,0]])
B = np.array([[6,0], [-1,2]])

In [64]:
print(A * B) #mnożenie element po elemencie

[[6 0]
 [2 0]]


In [68]:
print(np.dot(A, B)) #mnożenie macieżowe
print(A.dot(B))  #lub A @ B
print(B.dot(A))  #lub B @ A

[[  3   6]
 [-12   0]]
[[  3   6]
 [-12   0]]
[[ 6 18]
 [-5 -3]]


##Liczby pseudolosowe

In [69]:
np.random.seed(0)

In [70]:
np.random.randn(10)

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ])

In [76]:
np.random.randn(10,4) #rozkład normalny

array([[-1.22543552,  0.84436298, -1.00021535, -1.5447711 ],
       [ 1.18802979,  0.31694261,  0.92085882,  0.31872765],
       [ 0.85683061, -0.65102559, -1.03424284,  0.68159452],
       [-0.80340966, -0.68954978, -0.4555325 ,  0.01747916],
       [-0.35399391, -1.37495129, -0.6436184 , -2.22340315],
       [ 0.62523145, -1.60205766, -1.10438334,  0.05216508],
       [-0.739563  ,  1.5430146 , -1.29285691,  0.26705087],
       [-0.03928282, -1.1680935 ,  0.52327666, -0.17154633],
       [ 0.77179055,  0.82350415,  2.16323595,  1.33652795],
       [-0.36918184, -0.23937918,  1.0996596 ,  0.65526373]])

In [77]:
np.random.rand(10,4) #rozkład jednostajny na przedziale domyślnie [0,1)

array([[0.28173011, 0.58641017, 0.06395527, 0.4856276 ],
       [0.97749514, 0.87650525, 0.33815895, 0.96157015],
       [0.23170163, 0.94931882, 0.9413777 , 0.79920259],
       [0.63044794, 0.87428797, 0.29302028, 0.84894356],
       [0.61787669, 0.01323686, 0.34723352, 0.14814086],
       [0.98182939, 0.47837031, 0.49739137, 0.63947252],
       [0.36858461, 0.13690027, 0.82211773, 0.18984791],
       [0.51131898, 0.22431703, 0.09784448, 0.86219152],
       [0.97291949, 0.96083466, 0.9065555 , 0.77404733],
       [0.33314515, 0.08110139, 0.40724117, 0.23223414]])

In [86]:
A = np.random.randint(low=10, high=101, size=5) 
A

array([50, 70, 43, 38, 78])

In [88]:
np.random.choice(A) #równiez wartości typu 'str'

50

In [89]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
np.random.shuffle(data)
data

array([0, 1, 4, 2, 8, 6, 9, 7, 5, 3])

##Podstawowe funkcje

In [96]:
print(np.exp(1))
print(np.sqrt(9))

2.718281828459045
3.0


In [99]:
print(np.all([2,3,5]))
print(np.all([2,3,0]))

True
False


In [100]:
np.any([1, 2, 1])

True

In [102]:
A = np.random.rand(5)
A

array([0.2728219 , 0.3708528 , 0.19705428, 0.45985588, 0.0446123 ])

In [103]:
np.argmax(A)

3

In [105]:
A[np.argmax(A)]

0.4598558837560074

In [106]:
np.argsort(A)

array([4, 2, 0, 1, 3])

##Indeksowanie

In [108]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [111]:
# A[idx], A[start : stop], A[: stop], A[start :]
# tak samo jak w pythonie

In [113]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [117]:
A[0] #wiersze

array([0, 1, 2, 3, 4])

In [118]:
A[:, 0] #kolumny

array([ 0,  5, 10, 15])

In [121]:
A[1, 1] #konkretny element

6

In [123]:
A[1:3, 1:4] #fragment

array([[ 6,  7,  8],
       [11, 12, 13]])

##Iteracja po tablicach

In [124]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [126]:
for row in A:  #iterowanie po wierszach
    print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [131]:
for column in A.transpose():  #iterowanie po kolumnach
    print(column)

[ 0  5 10 15]
[ 1  6 11 16]
[ 2  7 12 17]
[ 3  8 13 18]
[ 4  9 14 19]


In [132]:
for item in A.flat:   #iterowanie po każdym elemencie
    print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


##Zmiana rozmiaru tablic

In [133]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [134]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [136]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

 ##Maski logiczne

In [138]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10,-1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [139]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [140]:
A[A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [142]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])